### ISSUE TITLE
info (ram, repo description)

### ISSUE THREAD

**Issue by NeoFromMatrix** [KalilDev/android_device_motorola_cedric#4]
Hello
Could you add a description (in the README.md) what the difference between this and the https://github.com/KalilDev/android_device_motorola_cedric-1 repo is?

I think the RAM spec is not correct. Usually (the standard model) it comes with 2GB, a 3GB model is available but not the default.

I'd also like to buy you a beer for motivation, just tell me how I can do it. Hoping also for twrp :)

cheers
Neo

**Comment by KalilDev** [comment]
@NeoFromMatrix Hey , yea , you are right , the 3gb variant isn't the standard , not even mine is 3gb, it wasn't me that made the readme.md , I will fix it. The -1 repo is because a guy kanged me , and that repo was me trying to pacifically solve this by having the correct ownership to my commits , tho the guy didn't accept and deleted his repo . I am making an TWRP tree, tho I'm really busy lately so I haven't had the time to test , therefore I didn't push it . Hey , much appreciated man , I have an PayPal account , tho it isnt on the same email address as my GitHub , contact me on telegram so I can send you the info . Thank you so much. Cheers.

**Comment by KalilDev** [comment]
@KalilDev My telegram is KalilDev.

**Comment by ab123321** [comment]
@KalilDev So unexpectable tho

**Comment by KalilDev** [comment]
@ab123321 Lol

**Comment by KalilDev** [comment]
@NeoFromMatrix Hey , this was fixed , look at the commit 
github.com/kalildev/android_device_motorola_cedric/commit/19c0ff56b85e81b17e0cf7a187bd7dd840085568
